### PR TITLE
Don't hide titlebar and fix icon

### PR DESCRIPTION
**Pull request by vivekkj123**
Hi,
  This PR aims to provide the title bar on top for resizing, and minimizing the window. This PR also fixes the bug of custom icon doesn't show on the dock. I've tested both on Linux and Windows.

### CODE REVIEW

**Comment by callmearta** [comment]
Why did you remove the OS check? on Mac the titlebar sucks and isn't pretty at all. It'd be nice if you add OS check and provide the menubar and titlebar only if user isn't a mac user.

**Comment by vivekkj123** [comment]
Added. Check now.

**Comment by vivekkj123** [comment]
@callmearta ☝

**Comment by callmearta** [comment]
Merging. Thank you

**Pull request merged**
