### PR TITLE
Fix Instagram nickname visibility in darkmode and Add a home button to channels/rooms 

### PR DESCRIPTION
**Pull request by stultus**
This PR handles two of the issues mentioned in  #33 

- Fixes the instagram/twitter username visibility issue in dark mode 
- Adds a home button in channels/rooms so that user can easily navigate to home without exiting from the room

### CODE REVIEW

**Comment by stultus** [comment]
Instagram username 
image

**Comment by stultus** [comment]
Home button in rooms
image

**Comment by callmearta** [comment]
Home button shouldn't be implemented just as a button to navigate to homepage. There's more to do before implementing such button, such as handling voice service and showing current room in homepage and also checking user's current room when he clicks on another room. So right now i won't merge this PR but thank you. If you managed to do those things do a new PR or complete this one.

**Comment by stultus** [comment]
@callmearta I understand the requirements, but the existing home button implementation on profiles also lacks these requirements. We can click on a random profile from the room and use the home button on their profile to navigate to the home page.  while I totally understand the requirement to implement this properly, having a home button in the room actually a minor enhancement. 
I believe that merging this PR won't affect the current state of usability in anyway. 

But if you are sure about not merging this now,  I can cherry-pick the instagram/twitter visibility issue commit and submit a separate PR,  feel free to close this PR.

**Comment by callmearta** [comment]
Yeah you're right. But the thing is users won't usually go to a person's profile and then click on the home button ( at least i think so ). Also the reason i had put it there was because in development stage i was always losing my browser history so i couldn't go back and needed a full refresh in application that's why i implemented home button in the first place. For now i think it's better if you cherry pick instagram/twitter visibility so people won't open issues about home button doing weird stuff. Thank you for your contribution mate.

**Pull request closed without merging**
